from __future__ import unicode_literals

from django.db import models

# Create your models here.

class File(models.Model):
    upload_date = models.DateTimeField(auto_now_add=True)
    #user_id
    #primary key autogenerated
    filename = models.CharField(max_length=100)
    raw = models.FileField(upload_to='uploads/%Y/%m/%d/')

class Expense(models.Model):
    date = models.DateField()
    category = models.CharField(max_length=100) # it might make more sense to make this column an enum
    employee_name = models.CharField(max_length=100)
    employee_address = models.CharField(max_length=100)
    expense_description = models.CharField(max_length=100)
    pre_tax_amount = models.DecimalField(max_digits=8, decimal_places=2)
    tax_name = models.CharField(max_length=100)
    tax_amount = models.DecimalField(max_digits=8, decimal_places=2)
    file = models.ForeignKey(File, on_delete=models.CASCADE)

